apiVersion: v1
kind: Service
metadata:
  name: web01-svc
  namespace: vdi
spec:
  selector:
    app: httpd01
  type: NodePort
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web01-dep
  namespace: vdi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: httpd01
  template:
    metadata:
      labels:
        app: httpd01
    spec:
      containers:
      - name: my-httpd
#-------------- v2.0 run httpd at foreground -----------------
        image: quay.io/toongm/my-httpd:v2.0
#        command: ["/bin/sh", "-ce", "tail -f /dev/null"]
